---
- name: ensure ssh key pair exists locally
  user: >
    name={{ ansible_user_id }}
    generate_ssh_key=yes
    ssh_key_file=.ssh/id_rsa

- name: ensure ssh public key exists on digitalocean
  digital_ocean: >
    state=present
    command=ssh
    name=ssh_pub_key
    ssh_pub_key={{ ssh_pub_key }}
    api_token={{ api_token }}
  register: ssh_pub_key
